### ISSUE TITLE
`just transform` command NOT running successfully

### ISSUE THREAD

**Issue by StuffbyYuki** [UN-OSAA/osaa-mvp#16]
There is an issue with `just transform`, not in the command itself, but how it has to do with the whole set up. 
1. If you run `just transform` directly in terminal after you ran the process in docker which creates `osaa_mvp.db`, sqlmesh will error out due to uncategorized changes - a change on the DB_PATH. With docker, the path would be `app/sqlMesh`, but with a just command, you'll use your absolute path on your file system. 

      sqlmesh error:
      ```
       import ibis                                                                                                                                                      
       import ibis.selectors as s                                                                                                                                       
      -DB_PATH = '/app/sqlMesh/osaa_mvp.db'                                                                                                                             
      +DB_PATH = '/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/sqlMesh/osaa_mvp.db'                                                                           
       def execute(context: ExecutionContext, start: datetime, end: datetime,                                                                                           
           execution_time: datetime, **kwargs: t.Any):                                                                                                                  
           con = ibis.duckdb.connect(DB_PATH)                                                                                                                           
      Directly Modified: intermediate__dev.wdi
      └── Indirectly Modified Children:
          └── intermediate__dev.wdi_country_averages
      Error: Can't apply a plan with uncategorized changes.
      error: Recipe `transform` failed on line 49 with exit code 1
      ```
      To reproduce this error, run: `docker compose run --rm pipeline etl` and then run `just ingest`, `just transform`
      
2. If you run `just transform` without `osaa_mvb.db` in place, you get a different error:
    ```
   2024-12-06 10:52:17,924 - MainThread - sqlmesh.core.context - ERROR - Apply Failure: Traceback (most recent call last):
    File "/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/.venv/lib/python3.11/site-packages/sqlmesh/utils/concurrency.py", line 227, in sequential_apply_to_dag
      fn(node)
    File "/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/.venv/lib/python3.11/site-packages/sqlmesh/utils/concurrency.py", line 165, in <lambda>
      lambda s_id: fn(snapshots_by_id[s_id]),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/.venv/lib/python3.11/site-packages/sqlmesh/core/snapshot/evaluator.py", line 300, in <lambda>
      lambda s: self._create_snapshot(
                ^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/.venv/lib/python3.11/site-packages/sqlmesh/core/snapshot/evaluator.py", line 708, in _create_snapshot
      evaluation_strategy.create(
    File "/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/.venv/lib/python3.11/site-packages/sqlmesh/core/snapshot/evaluator.py", line 1201, in create
      self.adapter.ctas(
    File "/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/.venv/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/shared.py", line 290, in internal_wrapper
      return func(*list_args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/.venv/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/base.py", line 494, in ctas
      return self._create_table_from_source_queries(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/.venv/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/base.py", line 688, in _create_table_from_source_queries
      self._create_table(
    File "/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/.venv/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/base.py", line 726, in _create_table
      self.execute(
    File "/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/.venv/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/base.py", line 1981, in execute
      self._execute(sql, **kwargs)
    File "/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/.venv/lib/python3.11/site-packages/sqlmesh/core/engine_adapter/base.py", line 1987, in _execute
      self.cursor.execute(sql, **kwargs)
    duckdb.duckdb.HTTPException: HTTP Error: HTTP GET error on 'https://osaa-mvp.s3.amazonaws.com/dev_yuki/landing/edu/OPRI_DATA_NATIONAL.parquet' (HTTP 400)
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/.venv/lib/python3.11/site-packages/sqlmesh/core/context.py", line 1253, in apply
        self._apply(plan, circuit_breaker)
      File "/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/.venv/lib/python3.11/site-packages/sqlmesh/core/context.py", line 1831, in _apply
        self._scheduler.create_plan_evaluator(self).evaluate(
      File "/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/.venv/lib/python3.11/site-packages/sqlmesh/core/plan/evaluator.py", line 115, in evaluate
        self._push(plan, snapshots, deployability_index_for_creation)
      File "/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/.venv/lib/python3.11/site-packages/sqlmesh/core/plan/evaluator.py", line 211, in _push
        self.snapshot_evaluator.create(
      File "/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/.venv/lib/python3.11/site-packages/sqlmesh/core/snapshot/evaluator.py", line 298, in create
        concurrent_apply_to_snapshots(
      File "/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/.venv/lib/python3.11/site-packages/sqlmesh/utils/concurrency.py", line 163, in concurrent_apply_to_snapshots
        return concurrent_apply_to_dag(
               ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/.venv/lib/python3.11/site-packages/sqlmesh/utils/concurrency.py", line 198, in concurrent_apply_to_dag
        return sequential_apply_to_dag(dag, fn, raise_on_error)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/Yuki/Desktop/Orem Data/Database Tycoon/osaa-mvp/.venv/lib/python3.11/site-packages/sqlmesh/utils/concurrency.py", line 230, in sequential_apply_to_dag
        raise NodeExecutionFailedError(node) from ex
    sqlmesh.utils.concurrency.NodeExecutionFailedError: Execution failed for node SnapshotId<"osaa_mvp"."opri"."data_national": 3723611953>
     (context.py:1261)
    Error: Failed processing SnapshotId<"osaa_mvp"."opri"."data_national": 3723611953>. HTTP Error: HTTP GET error on 'https://osaa-mvp.s3.amazonaws.com/dev_yuki/landing/edu/OPRI_DATA_NATIONAL.parquet' (HTTP 400)
    error: Recipe `transform_dry_run` failed on line 58 with exit code 1
    ```

**Comment by db-tycoon-stephen** [comment]
It seems we can solve this by deleting the local duckdb file before running the next command. I'm going to try that as I'm working today but we will need a longer-term solution.
It may be worthwhile to remove the steps in this process that persist a duck db file, just assume that s3 will be the only available storage. I'll dig into this today too

**Comment by db-tycoon-stephen** [comment]
This has been fixed
